/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author windows10
 */
public class AddLibrarianFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddLibrarianFrame
     */
    public AddLibrarianFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddLibrarianButton = new javax.swing.JButton();
        BackAddLibrarianButton = new javax.swing.JButton();
        LibrarianNameText = new javax.swing.JTextField();
        LibrarianEmailText = new javax.swing.JTextField();
        LibrarianContactNoText = new javax.swing.JTextField();
        LibrarianCityText = new javax.swing.JTextField();
        LibrarianAddressText = new javax.swing.JTextField();
        LibrarianPasswordText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Librarian");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("City:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Contact No:");

        AddLibrarianButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddLibrarianButton.setText("Add Librarian");
        AddLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLibrarianButtonActionPerformed(evt);
            }
        });

        BackAddLibrarianButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackAddLibrarianButton.setText("Back");
        BackAddLibrarianButton.setToolTipText("");
        BackAddLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackAddLibrarianButtonActionPerformed(evt);
            }
        });

        LibrarianNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarianNameTextActionPerformed(evt);
            }
        });

        LibrarianContactNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarianContactNoTextActionPerformed(evt);
            }
        });

        LibrarianPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarianPasswordTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(AddLibrarianButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(BackAddLibrarianButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(152, 152, 152))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LibrarianContactNoText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(62, 62, 62)
                                .addComponent(LibrarianCityText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(LibrarianAddressText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(LibrarianEmailText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LibrarianNameText)
                                    .addComponent(LibrarianPasswordText))
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LibrarianNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LibrarianPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LibrarianEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LibrarianAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LibrarianCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LibrarianContactNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(AddLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackAddLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLibrarianButtonActionPerformed
        // TODO add your handling code here:
        String name=LibrarianNameText.getText();
        String password=LibrarianPasswordText.getText();
        String email=LibrarianEmailText.getText();
        String address=LibrarianAddressText.getText();
        String city=LibrarianCityText.getText();
        String contact=LibrarianContactNoText.getText();
        String test="";
        
        int i=0,flag=1,check=1,flag2=0;
        
        if(name.compareTo(test)==0 || password.compareTo(test)==0 || email.compareTo(test)==0 || address.compareTo(test)==0 || city.compareTo(test)==0 || contact.compareTo(test)==0)
        {
           JOptionPane.showMessageDialog(null,"Error!");
           check=0;
        }
          
          if(name.compareTo(test)>0)
          {
             for(int h=0;h<name.length();h++)
              if(Character.isLetter(name.charAt(h))==false && name.charAt(h)!=' '){
                JOptionPane.showMessageDialog(null,"Error! Enter name in the form of letters");
                check=0;  
               }
          }
          
          for(int j=0; j<(email.length()); j++)
          {
               if(email.charAt(j)=='@')
                i++;
          }
          
          for(int m=0 ; m<contact.length() ; m++){
               if(Character.isLetter(contact.charAt(m))==true && contact.charAt(m)!=' ')
                    flag=0; }     
          
          if(email.compareTo(test)>0){
             if(email.charAt((email.length())-1)!='m'|| email.charAt((email.length())-2)!='o'|| email.charAt( (email.length())-3)!='c'|| email.charAt((email.length())-4)!='.'|| email.charAt((email.length())-5)=='@'|| i!=1)
            {
               JOptionPane.showMessageDialog(null,"Enter Email again!");
               check=0;
            }
          }
          
        if(city.compareTo(test)>0){
            for(int n=0;n<city.length();n++)
              if(Character.isLetter(city.charAt(n))==false && city.charAt(n)!=' '){
                JOptionPane.showMessageDialog(null,"Error! Enter city in the form of letters");
                check=0;
              }
        }
          
          int k= contact.length();
           if(k>11 || k<11 || (contact.charAt(0)!='0' || contact.charAt(1)!='1') || flag==0)
           {
            JOptionPane.showMessageDialog(null,"Enter contact again!");
             check=0;
           }

       if(check==1){
        try{
          File f=new File("librarian.txt");
          Scanner s = new Scanner(f);
          
          while(flag2==0 && s.hasNextLine()){
          String line=s.nextLine();
          String[] lib=line.split(",");
          String checkpass=lib[1];
          String checkemail=lib[2];
          String checkcontact=lib[5];
          if(password.compareTo(checkpass)==0)
          {
            flag2=1;
            JOptionPane.showMessageDialog(null,"Error! This password is already used");
            break;
           }
          if(email.compareTo(checkemail)==0)
          {
            flag2=1;
            JOptionPane.showMessageDialog(null,"Error! This email is already used");
            break;
           }
          if(contact.compareTo(checkcontact)==0)
          {
            flag2=1;
            JOptionPane.showMessageDialog(null,"Error! This contact is already used");
            break;
           }
          }
          
          if(check==1 && flag2==0){
              try{
            FileWriter addlibrarian = new FileWriter ("librarian.txt",true);
            addlibrarian.write(name+","+password+","+email+","+address+","+city+","+contact);
            addlibrarian.write(System.getProperty("line.separator"));
            addlibrarian.close();
            JOptionPane.showMessageDialog(null,"Librarian added successfully!");
            new AdminSectionFrame().setVisible(true);
            this.dispose();
              }
              catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
            }
          }
       }
          catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
        }
       }  
      
        
    }//GEN-LAST:event_AddLibrarianButtonActionPerformed

    private void LibrarianNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarianNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibrarianNameTextActionPerformed

    private void LibrarianPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarianPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibrarianPasswordTextActionPerformed

    private void BackAddLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackAddLibrarianButtonActionPerformed
        // TODO add your handling code here:
        new AdminSectionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackAddLibrarianButtonActionPerformed

    private void LibrarianContactNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarianContactNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibrarianContactNoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLibrarianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLibrarianButton;
    private javax.swing.JButton BackAddLibrarianButton;
    private javax.swing.JTextField LibrarianAddressText;
    private javax.swing.JTextField LibrarianCityText;
    private javax.swing.JTextField LibrarianContactNoText;
    private javax.swing.JTextField LibrarianEmailText;
    private javax.swing.JTextField LibrarianNameText;
    private javax.swing.JPasswordField LibrarianPasswordText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
