/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;

/**
 *
 * @author windows10
 */
public class LibrarianSectionFrame extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianSectionFrame
     */
    public LibrarianSectionFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddBooksLibrarianSectionButton = new javax.swing.JButton();
        ViewBooksButton = new javax.swing.JButton();
        IssueBooksButton = new javax.swing.JButton();
        ViewIssuedBooksButton = new javax.swing.JButton();
        ReturnBookLibrarianSectionButton = new javax.swing.JButton();
        LogoutLibrarianSectionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Librarian Section");

        AddBooksLibrarianSectionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddBooksLibrarianSectionButton.setText("Add Books");
        AddBooksLibrarianSectionButton.setPreferredSize(new java.awt.Dimension(130, 40));
        AddBooksLibrarianSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBooksLibrarianSectionButtonActionPerformed(evt);
            }
        });

        ViewBooksButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ViewBooksButton.setText("View Books");
        ViewBooksButton.setPreferredSize(new java.awt.Dimension(130, 40));
        ViewBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBooksButtonActionPerformed(evt);
            }
        });

        IssueBooksButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IssueBooksButton.setText("Issue Books");
        IssueBooksButton.setPreferredSize(new java.awt.Dimension(130, 40));
        IssueBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBooksButtonActionPerformed(evt);
            }
        });

        ViewIssuedBooksButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ViewIssuedBooksButton.setText("View Issued Books");
        ViewIssuedBooksButton.setPreferredSize(new java.awt.Dimension(130, 40));
        ViewIssuedBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewIssuedBooksButtonActionPerformed(evt);
            }
        });

        ReturnBookLibrarianSectionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ReturnBookLibrarianSectionButton.setText("Return Book");
        ReturnBookLibrarianSectionButton.setPreferredSize(new java.awt.Dimension(130, 40));
        ReturnBookLibrarianSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookLibrarianSectionButtonActionPerformed(evt);
            }
        });

        LogoutLibrarianSectionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogoutLibrarianSectionButton.setText("Logout");
        LogoutLibrarianSectionButton.setPreferredSize(new java.awt.Dimension(130, 40));
        LogoutLibrarianSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutLibrarianSectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBooksLibrarianSectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoutLibrarianSectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnBookLibrarianSectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewIssuedBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IssueBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(AddBooksLibrarianSectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ViewBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(IssueBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ViewIssuedBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ReturnBookLibrarianSectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LogoutLibrarianSectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewIssuedBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIssuedBooksButtonActionPerformed
        // TODO add your handling code here:
        new ViewIssuedBooksFrame().setVisible(true);
    }//GEN-LAST:event_ViewIssuedBooksButtonActionPerformed

    private void ReturnBookLibrarianSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookLibrarianSectionButtonActionPerformed
        // TODO add your handling code here:
        new ReturnBookFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnBookLibrarianSectionButtonActionPerformed

    private void AddBooksLibrarianSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBooksLibrarianSectionButtonActionPerformed
        // TODO add your handling code here:
        new AddBooksFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddBooksLibrarianSectionButtonActionPerformed

    private void LogoutLibrarianSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutLibrarianSectionButtonActionPerformed
        // TODO add your handling code here:
        new LibraryManagementFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutLibrarianSectionButtonActionPerformed

    private void ViewBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksButtonActionPerformed
        // TODO add your handling code here:
        new ViewBooksFrame().setVisible(true);
    }//GEN-LAST:event_ViewBooksButtonActionPerformed

    private void IssueBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBooksButtonActionPerformed
        // TODO add your handling code here:
        new IssueBookFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IssueBooksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianSectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianSectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianSectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianSectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianSectionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBooksLibrarianSectionButton;
    private javax.swing.JButton IssueBooksButton;
    private javax.swing.JButton LogoutLibrarianSectionButton;
    private javax.swing.JButton ReturnBookLibrarianSectionButton;
    private javax.swing.JButton ViewBooksButton;
    private javax.swing.JButton ViewIssuedBooksButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
