/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author windows10
 */
public class ReturnBookFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBookFrame
     */
    public ReturnBookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReturnCallNoText = new javax.swing.JTextField();
        ReturnStudentidText = new javax.swing.JTextField();
        ReturnBookButton = new javax.swing.JButton();
        BackReturnBookButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DaySpinner = new javax.swing.JSpinner();
        MonthSpinner = new javax.swing.JSpinner();
        YearSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Return Book");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Book Callno:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Student id:");

        ReturnStudentidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnStudentidTextActionPerformed(evt);
            }
        });

        ReturnBookButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ReturnBookButton.setText("Return Book");
        ReturnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookButtonActionPerformed(evt);
            }
        });

        BackReturnBookButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackReturnBookButton.setText("Back");
        BackReturnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackReturnBookButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Note!: Check the book properly!");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Day");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Month");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Year");

        DaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        MonthSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        YearSpinner.setModel(new javax.swing.SpinnerNumberModel(2021, 2021, 3000, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ReturnStudentidText)
                            .addComponent(ReturnCallNoText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ReturnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(BackReturnBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(YearSpinner)))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ReturnCallNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ReturnStudentidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ReturnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackReturnBookButton)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookButtonActionPerformed
        // TODO add your handling code here:
        String callno=ReturnCallNoText.getText();
        String id=ReturnStudentidText.getText();
        String day=DaySpinner.getValue().toString();
        String month=MonthSpinner.getValue().toString();
        String year=YearSpinner.getValue().toString();
        String test="";
        String Date=day+"-"+month+"-"+year;
       
        int check=0,issueid=0,flag=0;
        ArrayList<Issue> issues=new ArrayList<>();
        ArrayList<Book> books=new ArrayList<>();
        ArrayList<Student> students=new ArrayList<>();
        try{
          File f=new File("issue.txt");
          Scanner s = new Scanner(f);

          while(s.hasNextLine()){
          String line=s.nextLine();
          String[] str=line.split(",");
          Issue is=new Issue(str[0],str[1],str[2],str[3],str[4]);
          issues.add(is);
         }
          for(int i = 0; i < issues.size(); i++){
              if(callno.compareTo(issues.get(i).callno)==0 && id.compareTo(issues.get(i).studentid)==0){
               check=1;
               issueid=i;
               break;
              }
          }
          if(check==0)
             JOptionPane.showMessageDialog(null,"Error! Enter again"); 
         
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
          }
        
        if(Date.equals(issues.get(issueid).date)){
                   flag=1;
         }
        else{
           JOptionPane.showMessageDialog(null,"You have pentality!");
                   flag=1;
        }
        
        try{
          File f=new File("books.txt");
          Scanner s = new Scanner(f);
          while(s.hasNextLine()){
          String line=s.nextLine();
          String[] str=line.split(",");
          Book b=new Book(str[0],str[1],str[2],str[3],Integer.parseInt(str[4]),str[5],Integer.parseInt(str[6]));
          books.add(b);
          }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
          }
          
        try{
          File f=new File("Student.txt");
          Scanner s = new Scanner(f);
          while(s.hasNextLine()){
          String line=s.nextLine();
          String[] str=line.split(",");
          Student st=new Student(str[0],str[1],str[2],str[3],str[4],str[5],Integer.parseInt(str[6]));
          students.add(st);
         }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
          }
        
        if(check==1 && flag==1){
            for(int i=0;i<books.size();i++){
              if(callno.compareTo(books.get(i).callno)==0){
                  books.get(i).quantity++;
                  books.get(i).issued--;
              }
            }
     
             students.get(Integer.parseInt(id)-1).issued--;
             
            issues.remove(issueid);
             try{
            for(int i=0;i<issues.size();i++){
            if(i==0){
            FileWriter writer = new FileWriter ("issue.txt");
            writer.write(issues.get(i).callno+","+issues.get(i).studentid+","+issues.get(i).studentname+","+issues.get(i).studentcontact+","+issues.get(i).date);
            writer.write(System.getProperty("line.separator"));
            writer.close();
              }
            else{
            FileWriter writer = new FileWriter ("issue.txt",true);
            writer.write(issues.get(i).callno+","+issues.get(i).studentid+","+issues.get(i).studentname+","+issues.get(i).studentcontact+","+issues.get(i).date);
            writer.write(System.getProperty("line.separator"));
            writer.close();
                }
            }
          }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
          }
             
             try{
            for(int j=0;j<books.size();j++){
             if(j==0){
            FileWriter writer = new FileWriter ("books.txt");
            writer.write(books.get(j).callno+","+books.get(j).name+","+books.get(j).author+","+books.get(j).publisher+","+books.get(j).quantity+","+books.get(j).date+","+books.get(j).issued);
            writer.write(System.getProperty("line.separator"));
            writer.close();
             }
            else{
            FileWriter writer = new FileWriter ("books.txt",true);
            writer.write(books.get(j).callno+","+books.get(j).name+","+books.get(j).author+","+books.get(j).publisher+","+books.get(j).quantity+","+books.get(j).date+","+books.get(j).issued);
            writer.write(System.getProperty("line.separator"));
            writer.close();
               }
            }
           }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
          }
             
         try{
            for(int i=0;i<students.size();i++){
            if(i==0){
            FileWriter writer = new FileWriter ("Student.txt");
            writer.write(students.get(i).name+","+students.get(i).password+","+students.get(i).email+","+students.get(i).address+","+students.get(i).city+","+students.get(i).contact+","+students.get(i).issued);
            writer.write(System.getProperty("line.separator"));
            writer.close();
              }
            else{
            FileWriter writer = new FileWriter ("Student.txt",true);
            writer.write(students.get(i).name+","+students.get(i).password+","+students.get(i).email+","+students.get(i).address+","+students.get(i).city+","+students.get(i).contact+","+students.get(i).issued);
            writer.write(System.getProperty("line.separator"));
            writer.close();
                }
            }
          }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!");
          }
         
         JOptionPane.showMessageDialog(null,"Book returned successfully!!");
         new LibrarianSectionFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ReturnBookButtonActionPerformed

    private void BackReturnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackReturnBookButtonActionPerformed
        // TODO add your handling code here:
        new LibrarianSectionFrame().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BackReturnBookButtonActionPerformed

    private void ReturnStudentidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnStudentidTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnStudentidTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackReturnBookButton;
    private javax.swing.JSpinner DaySpinner;
    private javax.swing.JSpinner MonthSpinner;
    private javax.swing.JButton ReturnBookButton;
    private javax.swing.JTextField ReturnCallNoText;
    private javax.swing.JTextField ReturnStudentidText;
    private javax.swing.JSpinner YearSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
